name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "lib/**/*"
      - "test/**/*"
      - "native/**/*"

env:
  MIX_ENV: test
  BLAKE3_BUILD: true

jobs:
  test:
    name: Elixir ${{ matrix.pair.elixir }} / OTP ${{ matrix.pair.otp }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.14.3
              otp: 25.2.1
          - pair:
              elixir: 1.15.6
              otp: 26.1
            lint: lint
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1.15
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}

      - name: Install minimal stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Check unused deps
        run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Compile deps
        run: mix deps.compile

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Test
        run: mix test
